version: '3'

services:
  web1:
    image: tejamedida/my-hello-world:1
    ports:
      - 9000:3000
  web2:
    image: tejamedida/my-hello-world:1
    ports:
      - 9001:3000
  web3:
    image: tejamedida/my-hello-world:1
    ports:
      - 9002:3000